### ISSUE TITLE
PATCH users - error with object_types primary key NULL

### ISSUE THREAD

**Issue by didoda** [bedita/bedita#1068] opened 2017-01-30 09:46 UTC
PATCH users throws an exception in "/var/www/workspace/bedita4/plugins/BEdita/Core/src/Model/Table/ObjectTypesTable.php"
```
Record not found in table \"object_types\" with primary key [NULL]
```
Example of json data in body:
```
{
    "data": {
        "id": "{{userId}}",
        "type": "users",
        "attributes": {
            "name": "John"
        }
    }
}
```
Url: {{be4Url}}/users/{{userId}}
......
local env:
```
$ php --version
PHP 5.6.30-1+deb.sury.org~yakkety+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
```

**Comment by batopa** [comment] 2017-01-30 12:13
I can't reproduce it. Maybe an environment issue?

**Comment by didoda** [comment] 2017-01-30 12:35
seems to be reproduced with PHP 5.6.30-1

**Comment by batopa** [comment] 2017-01-30 12:43
Upgrading PHP to 5.6.30 I have several unit tests failure too. I'm trying to investigate the issues.

**Comment by batopa** [comment] 2017-01-31 09:04
This issue refers to https://github.com/cakephp/cakephp/pull/10127
Applying the patch of the PR all works as expected. The PR is already merged on CakePHP master branch, we need to wait for the next CakePHP release.
Closing

**Closed as completed by batopa** 2017-01-31 09:04 UTC
